# Broadcasting

In [2]:
import tensorflow as tf

In [3]:
# a+b的过程就使用了Broadcasting
# 首先a相对于b属于维度更高，两者的维度是不匹配的
# b会从低维开始进行填充  [3] => [1,1,1,3]
# 之后与a的size进行匹配 [1,1,1,3] => [4,32,32,3]
# 最后经过brodcasting的b，可以与a进行相加操作
a = tf.random.normal([4,32,32,3])
b = tf.random.normal([3])
(a+b).shape

TensorShape([4, 32, 32, 3])

In [4]:
# [32,32,1] => [1,32,32,1]
# [1,32,32,1] => [4,32,32,3]
a = tf.random.normal([4,32,32,3])
b = tf.random.normal([32,32,1])
(a+b).shape

TensorShape([4, 32, 32, 3])

In [6]:
# [4,1,1,1] => [4,32,32,3]
a = tf.random.normal([4,32,32,3])
b = tf.random.normal([4,1,1,1])
(a+b).shape

TensorShape([4, 32, 32, 3])

In [8]:
# a = tf.random.normal([4,32,32,3])
# b = tf.random.normal([1,4,1,1])
# (a+b).shape

# [1,4,1,1]中4不能Broadcasting到32
# InvalidArgumentError: Incompatible shapes: [4,32,32,3] vs. [1,4,1,1] [Op:Add] name: add/

# tf.broadcast_to

In [9]:
a = tf.random.normal([4,32,32,3])
(a+tf.random.normal([4,1,1,1])).shape

TensorShape([4, 32, 32, 3])

In [12]:
# broadcating自动发生在a+b的过程中
# 这一自动broadcating的过程可以使用 tf.broadcating_to 来实现
b = tf.broadcast_to(tf.random.normal([4,1,1,1]),[4,32,32,3])
b.shape

TensorShape([4, 32, 32, 3])

# broadcasting vs tile

In [25]:
a = tf.ones([3,4])
a1 = tf.broadcast_to(a,[2,3,4])
a1

<tf.Tensor: id=137, shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [26]:
a2 = tf.expand_dims(a, axis=0)
a2

<tf.Tensor: id=140, shape=(1, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [27]:
a2 = tf.tile(a2,[2,1,1])
a2

<tf.Tensor: id=143, shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>