# tf.norm

Vector norm 的方法

In [1]:
import tensorflow as tf

In [7]:
a = tf.ones([2,2])
print(tf.norm(a))
print(tf.sqrt(tf.reduce_sum(tf.square(a))))

tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [9]:
a = tf.ones([4,28,28,3])
print(tf.norm(a))
print(tf.sqrt(tf.reduce_sum(tf.squeeze(a))))

tf.Tensor(96.99484, shape=(), dtype=float32)
tf.Tensor(96.99484, shape=(), dtype=float32)


In [16]:
# L1 Norm

b = tf.ones([2,2])
print(tf.norm(b))
print(tf.norm(b,ord=2,axis=1))
print(tf.norm(b,ord=1))
print(tf.norm(b,ord=1,axis=0))
print(tf.norm(b,ord=1,axis=1))

tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor([1.4142135 1.4142135], shape=(2,), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor([2. 2.], shape=(2,), dtype=float32)
tf.Tensor([2. 2.], shape=(2,), dtype=float32)


# reduce_min/max/me

In [18]:
a = tf.random.normal([4,10])
# 最小值,最大值,平均值
tf.reduce_min(a),tf.reduce_max(a),tf.reduce_mean(a)

(<tf.Tensor: id=216, shape=(), dtype=float32, numpy=-2.253754>,
 <tf.Tensor: id=218, shape=(), dtype=float32, numpy=2.6642056>,
 <tf.Tensor: id=220, shape=(), dtype=float32, numpy=0.0904077>)

In [19]:
tf.reduce_min(a,axis=1),tf.reduce_max(a,axis=1),tf.reduce_mean(a,axis=1)

(<tf.Tensor: id=225, shape=(4,), dtype=float32, numpy=array([-2.253754 , -1.4311816, -1.2286372, -1.1156268], dtype=float32)>,
 <tf.Tensor: id=227, shape=(4,), dtype=float32, numpy=array([2.6642056, 1.4913954, 1.9070715, 0.9904951], dtype=float32)>,
 <tf.Tensor: id=229, shape=(4,), dtype=float32, numpy=array([ 0.44928694, -0.13833386, -0.03505407,  0.08573177], dtype=float32)>)

# argmax/argmin

In [21]:
a = tf.random.normal([4,10])
print(tf.argmax(a).shape)
print(tf.argmax(a))
print(tf.argmin(a).shape)

(10,)
tf.Tensor([0 0 3 3 0 0 2 3 3 3], shape=(10,), dtype=int64)
(10,)


# tf.equal

In [25]:
a = tf.constant([1,2,3,4,5])
b = tf.range(5)

res = tf.equal(a, b)
print(res)
print(tf.reduce_sum(tf.cast(res, dtype=tf.int32)))

tf.Tensor([False False False False False], shape=(5,), dtype=bool)
tf.Tensor(0, shape=(), dtype=int32)


In [31]:
# Accuracy

a = tf.reshape(tf.constant([0.1, 0.2, 0.7, 0.9, 0.05, 0.05]),[2,3])
a

<tf.Tensor: id=299, shape=(2, 3), dtype=float32, numpy=
array([[0.1 , 0.2 , 0.7 ],
       [0.9 , 0.05, 0.05]], dtype=float32)>

In [33]:
pred = tf.cast(tf.argmax(a, axis=1), dtype=tf.int32)
y = tf.constant([2, 1])

pred, y

(<tf.Tensor: id=307, shape=(2,), dtype=int32, numpy=array([2, 0], dtype=int32)>,
 <tf.Tensor: id=308, shape=(2,), dtype=int32, numpy=array([2, 1], dtype=int32)>)

In [34]:
tf.equal(y, pred)

<tf.Tensor: id=311, shape=(2,), dtype=bool, numpy=array([ True, False])>

In [35]:
correct = tf.reduce_sum(tf.cast(tf.equal(y, pred),dtype=tf.int32))
accuracy = correct/2
correct, accuracy

(<tf.Tensor: id=316, shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: id=320, shape=(), dtype=float64, numpy=0.5>)

# tf.unique

In [36]:
a = tf.range(5)
b = tf.constant([2,4,4,3,2])

tf.unique(a), tf.unique(b)

(Unique(y=<tf.Tensor: id=328, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>, idx=<tf.Tensor: id=329, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>),
 Unique(y=<tf.Tensor: id=330, shape=(3,), dtype=int32, numpy=array([2, 4, 3], dtype=int32)>, idx=<tf.Tensor: id=331, shape=(5,), dtype=int32, numpy=array([0, 1, 1, 2, 0], dtype=int32)>))