# 填充与复制

- pad
- tile
- broadcast_to

In [1]:
import tensorflow as tf

In [8]:
# pad
a = tf.reshape(tf.range(9), [3,3])

tf.pad(a,[[0,0],[0,0]]),tf.pad(a,[[1,0],[0,0]])

(<tf.Tensor: id=53, shape=(3, 3), dtype=int32, numpy=
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=int32)>,
 <tf.Tensor: id=55, shape=(4, 3), dtype=int32, numpy=
 array([[0, 0, 0],
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=int32)>,
 <tf.Tensor: id=57, shape=(4, 3), dtype=int32, numpy=
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [0, 0, 0]], dtype=int32)>)

In [10]:
tf.pad(a,[[1,1],[0,0]]), tf.pad(a,[[1,1],[1,1]])

(<tf.Tensor: id=65, shape=(5, 3), dtype=int32, numpy=
 array([[0, 0, 0],
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [0, 0, 0]], dtype=int32)>,
 <tf.Tensor: id=67, shape=(5, 5), dtype=int32, numpy=
 array([[0, 0, 0, 0, 0],
        [0, 0, 1, 2, 0],
        [0, 3, 4, 5, 0],
        [0, 6, 7, 8, 0],
        [0, 0, 0, 0, 0]], dtype=int32)>)

In [11]:
# image padding

a = tf.random.normal([4,28,28,3])
b = tf.pad(a, [[0,0],[2,2],[2,2],[0,0]])

b.shape

TensorShape([4, 32, 32, 3])

In [12]:
# tile
# repeat data along dim n times
# [a,b,c],2 => [a,b,c,a,b,c]

a = tf.reshape(tf.range(9), [3,3])
tf.tile(a,[1,2]), tf.tile(a,[2,1]), tf.tile(a,[2,2])

(<tf.Tensor: id=85, shape=(3, 6), dtype=int32, numpy=
 array([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5],
        [6, 7, 8, 6, 7, 8]], dtype=int32)>,
 <tf.Tensor: id=87, shape=(6, 3), dtype=int32, numpy=
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=int32)>,
 <tf.Tensor: id=89, shape=(6, 6), dtype=int32, numpy=
 array([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5],
        [6, 7, 8, 6, 7, 8],
        [0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5],
        [6, 7, 8, 6, 7, 8]], dtype=int32)>)

In [14]:
# tile VS broadcast_to

a = tf.random.normal([4,28,28,3])
aa = tf.expand_dims(a, axis=0)
tf.tile(aa, [2,1,1])

InvalidArgumentError: Expected multiples argument to be a vector of length 5 but got length 3 [Op:Tile]