# 数据统计

- tf.normal
- tf.reduce_min/max
- tf.argmax/argmin
- tf.equal
- tf.unique

In [1]:
import tensorflow as tf

In [2]:
# tf.norm

a = tf.ones([2,2])

print(tf.norm(a))
print(tf.sqrt(tf.reduce_sum(tf.square(a))))

tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [6]:
# L1 Norm

b = tf.ones([2,2])

print(tf.norm(b))
print(tf.norm(b,ord=2,axis=1))
print(tf.norm(b,ord=1))
print(tf.norm(b,ord=1,axis=0))
print(tf.norm(b,ord=1,axis=1))

tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor([1.4142135 1.4142135], shape=(2,), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor([2. 2.], shape=(2,), dtype=float32)
tf.Tensor([2. 2.], shape=(2,), dtype=float32)


In [7]:
# reduce_min/max/mean

a = tf.random.normal([4,10])

tf.reduce_min(a), tf.reduce_max(a), tf.reduce_mean(a)

(<tf.Tensor: id=71, shape=(), dtype=float32, numpy=-2.2923238>,
 <tf.Tensor: id=73, shape=(), dtype=float32, numpy=2.6107056>,
 <tf.Tensor: id=75, shape=(), dtype=float32, numpy=0.19523866>)

In [8]:
tf.reduce_min(a, axis=1), tf.reduce_max(a, axis=1), tf.reduce_mean(a, axis=1)

(<tf.Tensor: id=80, shape=(4,), dtype=float32, numpy=array([-2.2923238, -0.6402987, -1.1174372, -1.5473856], dtype=float32)>,
 <tf.Tensor: id=82, shape=(4,), dtype=float32, numpy=array([1.6690364, 2.6107056, 0.7928473, 1.4002668], dtype=float32)>,
 <tf.Tensor: id=84, shape=(4,), dtype=float32, numpy=array([-0.01732296,  0.5770308 ,  0.0246646 ,  0.19658226], dtype=float32)>)

In [9]:
# argmax/argmin

a = tf.random.normal([4,10])

a.shape, tf.argmax(a), tf.argmax(a).shape, tf.argmin(a).shape

(TensorShape([4, 10]),
 <tf.Tensor: id=95, shape=(10,), dtype=int64, numpy=array([1, 3, 1, 1, 0, 1, 2, 2, 2, 0])>,
 TensorShape([10]),
 TensorShape([10]))

In [10]:
# tf.equal

a = tf.constant([1,2,3,2,5])
b = tf.range(5)

tf.equal(a, b)

<tf.Tensor: id=106, shape=(5,), dtype=bool, numpy=array([False, False, False, False, False])>

In [11]:
res = tf.equal(a, b)
tf.reduce_sum(tf.cast(res, dtype=tf.int32))

<tf.Tensor: id=111, shape=(), dtype=int32, numpy=0>

In [19]:
# Accuracy

a = tf.reshape(tf.constant([0.1, 0.2, 0.7, 0.9, 0.05, 0.05]),[2,3])
pred = tf.cast(tf.argmax(a,axis=1), dtype=tf.int32)
y = tf.constant([2,1])
correct = tf.reduce_sum(tf.cast(tf.equal(y, pred),dtype=tf.int32))
accuracy = correct / 2

accuracy

<tf.Tensor: id=182, shape=(), dtype=float64, numpy=0.5>

In [20]:
# tf.unique

a = tf.range(5)
tf.unique(a)

Unique(y=<tf.Tensor: id=188, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>, idx=<tf.Tensor: id=189, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>)

In [21]:
a = tf.constant([4,2,2,4,3])
tf.unique(a)

Unique(y=<tf.Tensor: id=193, shape=(3,), dtype=int32, numpy=array([4, 2, 3], dtype=int32)>, idx=<tf.Tensor: id=194, shape=(5,), dtype=int32, numpy=array([0, 1, 1, 0, 2], dtype=int32)>)