# 高阶op补充

- where
- scatter_nd
- meshgrid

In [2]:
import tensorflow as tf

In [3]:
# where
a = tf.random.normal([3,3])
mask = a>0

a, mask

(<tf.Tensor: id=5, shape=(3, 3), dtype=float32, numpy=
 array([[-0.37064484,  0.20893477,  0.5041223 ],
        [ 0.930172  , -0.7504607 ,  0.35308376],
        [ 1.0158533 , -0.14240764, -0.8788261 ]], dtype=float32)>,
 <tf.Tensor: id=7, shape=(3, 3), dtype=bool, numpy=
 array([[False,  True,  True],
        [ True, False,  True],
        [ True, False, False]])>)

In [4]:
# 通过 mask 及 boolean_mask 可以将 >0 的值都选出来
# 同样的需求也可以通过 where 实现
tf.boolean_mask(a, mask)

<tf.Tensor: id=36, shape=(5,), dtype=float32, numpy=
array([0.20893477, 0.5041223 , 0.930172  , 0.35308376, 1.0158533 ],
      dtype=float32)>

In [6]:
indices = tf.where(mask)
indices

<tf.Tensor: id=39, shape=(5, 2), dtype=int64, numpy=
array([[0, 1],
       [0, 2],
       [1, 0],
       [1, 2],
       [2, 0]])>

In [7]:
tf.gather_nd(a, indices)

<tf.Tensor: id=41, shape=(5,), dtype=float32, numpy=
array([0.20893477, 0.5041223 , 0.930172  , 0.35308376, 1.0158533 ],
      dtype=float32)>